### PR TITLE
use segment scan equal to capacity size

### PR DESCRIPTION
**Pull request by mcwhittemore**
I still need to vet that this solves the bottleneck we're seeing with high cpu, low i/o migrations.

### CODE REVIEW

**Comment by rclark** [comment]
Yeah I think that we'd benefit more from being able to run multiple processes, and specify a segment ID for each one.

**Comment by mcwhittemore** [comment]
my fear is that that is a pretty big breaking change (which we should do). I'd like to see what the gains for this are first.

**Comment by rclark** [comment]
I am confident that these gains are trivial. This is fundamentally the same as increasing the concurrency on a single scan. You're still going to be constrained by synchronous work on a single process.

I don't think that adding an optional `--segment` flag to the CLI needs to be such a big breaking change, does it?

**Comment by mcwhittemore** [comment]
> You're still going to be constrained by synchronous work on a single process

Yep, but you won't be constrained by a single poll which I suspect (I don't have proof) is 1/4 of the problem.

I'm good with killing this attempt. It is more here to let me test my hunch above than anything else.

> I don't think that adding an optional --segment flag to the CLI needs to be such a big breaking change, does it?

No matter how we do this, the ability to use closure scope to share state between jobs is going to be lost.

`--segment` is a nice way to make this its own feature, but it complicates the API. I'd prefer we did this via `--concurrency`. One gain of using `--concurrency` is that we could map this functionality to `query` and `stream` in the future.

*query is not a feature now, but I think it should be, opening that issue*

**Pull request closed without merging**
